"""add activities table

Revision ID: 3744c5962afa
Revises: f5c8be02576c
Create Date: 2026-06-11 06:46:02.359796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3744c5962afa'
down_revision: Union[str, Sequence[str], None] = 'f5c8be02576c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('board_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activities_actor_id', 'activities', ['actor_id'], unique=False)
    op.create_index('ix_activities_board_id_created_at', 'activities', ['board_id', 'created_at'], unique=False)
    op.create_index('ix_activities_project_id_created_at', 'activities', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_activities_task_id_created_at', 'activities', ['task_id', 'created_at'], unique=False)
    op.create_index('ix_activities_workspace_id_created_at', 'activities', ['workspace_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activities_workspace_id_created_at', table_name='activities')
    op.drop_index('ix_activities_task_id_created_at', table_name='activities')
    op.drop_index('ix_activities_project_id_created_at', table_name='activities')
    op.drop_index('ix_activities_board_id_created_at', table_name='activities')
    op.drop_index('ix_activities_actor_id', table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
