"""add mentions table

Revision ID: 82b96ba9e60d
Revises: 86115e225e8b
Create Date: 2026-06-09 09:13:56.332036

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "82b96ba9e60d"
down_revision: Union[str, Sequence[str], None] = "86115e225e8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mentions",
        sa.Column("comment_id", sa.Uuid(), nullable=False),
        sa.Column("mentioned_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"], ["task_comments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["mentioned_user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "comment_id", "mentioned_user_id", name="uq_mentions_comment_user"
        ),
    )
    op.create_index(
        "ix_mentions_mentioned_user_id", "mentions", ["mentioned_user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mentions_mentioned_user_id", table_name="mentions")
    op.drop_table("mentions")
    # ### end Alembic commands ###
