"""add favorites and user board preferences

Revision ID: f5c8be02576c
Revises: 4bb26a8ac9da
Create Date: 2026-06-11 06:14:50.961833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c8be02576c'
down_revision: Union[str, Sequence[str], None] = '4bb26a8ac9da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_id', name='uq_favorites_user_entity_id')
    )
    op.create_index('ix_favorites_entity', 'favorites', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_favorites_user_id', 'favorites', ['user_id'], unique=False)
    op.create_table('user_board_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('view_type', sa.String(length=20), server_default='board', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'board_id', name='uq_user_board_preferences_user_board')
    )
    op.create_index('ix_user_board_preferences_board_id', 'user_board_preferences', ['board_id'], unique=False)
    op.create_index('ix_user_board_preferences_user_id', 'user_board_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_board_preferences_user_id', table_name='user_board_preferences')
    op.drop_index('ix_user_board_preferences_board_id', table_name='user_board_preferences')
    op.drop_table('user_board_preferences')
    op.drop_index('ix_favorites_user_id', table_name='favorites')
    op.drop_index('ix_favorites_entity', table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
